name: React Build and Deploy

on:
  push:
    branches:
      - main # Triggers the action when code is pushed to the main branch
  pull_request:
    branches:
      - main # Also triggers on pull requests to main branch

jobs:
  build:
    runs-on: ubuntu-latest # Defines the environment (Ubuntu in this case)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Checkout the repository's code

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22" # Set the Node.js version you want to use

      - name: Install dependencies
        run: |
          npm install  # Install npm dependencies defined in package.json

      - name: Run Build
        run: |
          npm run build  # Run the build script from package.json
